---
language: go

go:
  - 1.13.x
  
before_install:
  - go get -t -v ./...
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - go get github.com/corsc/go-tools/package-coverage

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - ls -al
  - bash <(curl -s https://codecov.io/bash)