---
language: go

go:
  - 1.13.x
  
before_install:
  - go get -t -v ./...
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - go get github.com/corsc/go-tools/package-coverage

script:
  - package-coverage -c -a=0 ./
  # - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - find . -name "profile.cov" -type f | xargs sed -i -e "/fake_code/d"
  - gocov convert profile.cov | gocov-xml > coverage.xml
  - ls -al
  - cat profile.cov
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml