---
language: go

go:
  - 1.13.x
  
before_install:
  - go get -t -v ./...
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - go get github.com/corsc/go-tools/package-coverage

script:
  - package-coverage -c -a=0 ./
  # - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - find ./* -name "profile.cov" -type f | xargs sed -i -e "/fake_code/d"
  - find ./* -name "profile.cov" -type f -exec sh -c 'gocov convert {} | gocov-xml > {}.xml' \;
  - ls -al
  - ls -al pkg2/
  - cat profile.cov
  - curl -s "https://codecov.gitlab.myteksi.net/bash" | \
    bash -s - -f "*.cov.xml"