---
language: go

go:
  - 1.13.x
  
before_install:
  - go get -t -v ./...
  - go get github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - gocov convert coverage.txt | gocov-xml > coverage.xml
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml